"use client";

import Link from "next/link";
import { ArrowRightIcon } from "lucide-react";

import { deriveFixPlan, deriveTopProblems } from "@/lib/grader/scoring";
import type { AuditReport } from "@/lib/grader/types";
import { cn } from "@/lib/utils";

import { AuditScopeBanner } from "@/components/grader/audit-scope-banner";
import { ImproveWithAICTA, StickyFixCTA } from "./ctas";
import { FixPlanSection } from "./fix-plan";
import { GuestExperienceSection } from "./guest-experience";
import { LocalListingsSection } from "./local-listings";
import { ScoreHero } from "./score-hero";
import { SearchVisibilitySection } from "./search-visibility";
import { ReviewedItemsSummary, WebsiteSeoChecklist } from "./seo-checklist";
import { TopSummaryGrid } from "./summary-cards";
import { UnlockModal } from "./unlock-modal";

/** Deterministic (UTC, fixed locale) so server and client render identically. */
function formatAuditDate(iso: string): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(iso));
}

function ReportHeader({ signedIn }: { signedIn: boolean }) {
  return (
    <header className="sticky top-0 z-30 border-b border-black/5 bg-[#faf7ef]/85 backdrop-blur-lg">
      <div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-4 py-3 sm:px-6">
        <Link href="/" className="flex items-center gap-2">
          <span className="flex size-7 items-center justify-center rounded-lg bg-emerald-600 text-sm font-bold text-white">
            L
          </span>
          <span className="font-semibold text-zinc-900">
            LocalSync <span className="font-normal text-zinc-500">Grader</span>
          </span>
        </Link>
        <div className="flex items-center gap-2">
          <Link
            href="/grader"
            className="hidden text-sm font-medium text-zinc-600 hover:text-zinc-900 sm:block"
          >
            Grade another business
          </Link>
          <Link
            href={signedIn ? "/dashboard" : "/sign-up"}
            className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-emerald-600 px-3.5 text-sm font-semibold text-white transition-colors hover:bg-emerald-700"
          >
            {signedIn ? "Dashboard" : "Get LocalSync"}
            <ArrowRightIcon className="size-3.5" />
          </Link>
        </div>
      </div>
    </header>
  );
}

export function GraderReport({
  report,
  signedIn,
}: {
  report: AuditReport;
  signedIn: boolean;
}) {
  const locked = !report.leadCaptured;
  const problems = deriveTopProblems({
    checks: report.checks,
    keywords: report.keywords,
    hasWebsite: report.websiteUrl !== null,
  });
  const fixPlan = deriveFixPlan(report.checks);

  return (
    <div className="min-h-full bg-[#faf7ef]">
      <ReportHeader signedIn={signedIn} />

      <main
        className={cn(
          "mx-auto max-w-5xl space-y-5 px-4 py-6 sm:px-6 sm:py-8",
          locked && "pointer-events-none blur-md select-none",
        )}
        aria-hidden={locked}
      >
        <AuditScopeBanner
          operatingModel={report.operatingModel}
          auditTier={report.auditTier}
          gbpLinked={report.gbpProfile.gbpLinked !== false}
          className="mb-1"
        />
        <ScoreHero report={report} />
        <TopSummaryGrid report={report} problems={problems} />
        <SearchVisibilitySection report={report} />
        <ReviewedItemsSummary report={report} />
        <WebsiteSeoChecklist report={report} />
        <GuestExperienceSection report={report} />
        <LocalListingsSection report={report} />
        <FixPlanSection fixPlan={fixPlan} />
        <ImproveWithAICTA report={report} signedIn={signedIn} />

        <footer className="pt-4 pb-16 text-center text-xs text-zinc-400">
          <p>
            Audit generated by LocalSync Grader ·{" "}
            {formatAuditDate(report.createdAt)} · scores reflect publicly
            visible signals at scan time.
          </p>
        </footer>
      </main>

      {locked ? (
        <UnlockModal report={report} />
      ) : (
        <StickyFixCTA report={report} signedIn={signedIn} />
      )}
    </div>
  );
}
