/**
 * Full-res photography crawled from localmap.co (Jul 2026).
 * Real Local Map Co. client / field work — used as marketing surface texture.
 */

export const HERO_TEXTURE = {
  primary: "/texture/hero-chamber.jpg",
  secondary: "/texture/hero-still.jpg",
  tertiary: "/texture/hero-facility.jpg",
  accent: "/texture/hero-team.jpg",
} as const;

export const CLIENT_ARCHIVE_WORK = [
  {
    src: "/reviews/recent/anhai-society.png",
    alt: "Anhai Society Cannabis and Company website experience",
    client: "Anhai Society",
    kind: "Website",
    era: "Recent",
    caption: "A premium cannabis experience shaped around place and community.",
  },
  {
    src: "/reviews/recent/biolight-labs.png",
    alt: "BioLight Labs research materials website",
    client: "BioLight Labs",
    kind: "Website",
    era: "Recent",
    caption: "A documentation-first research storefront built for buyer confidence.",
  },
  {
    src: "/reviews/recent/biolight-shop.png",
    alt: "BioLight mitochondrial wellness ecommerce creative",
    client: "BioLight",
    kind: "Ecommerce",
    era: "Recent",
    caption: "A vivid wellness storefront connecting science, products, and education.",
  },
  {
    src: "/reviews/recent/lieus-asian-bistro.png",
    alt: "Lieu's Asian Bistro website homepage",
    client: "Lieu's Asian Bistro",
    kind: "Website",
    era: "Recent",
    caption: "A restaurant experience built around discovery, events, and ordering.",
  },
  {
    src: "/reviews/recent/baskin-jones.png",
    alt: "Baskin Jones Law website homepage",
    client: "Baskin Jones Law",
    kind: "Website",
    era: "Recent",
    caption: "A focused legal presence that makes help easy to find and act on.",
  },
  {
    src: "/reviews/recent/blockbusters-tech.png",
    alt: "Block Busters Tech website homepage",
    client: "Block Busters Tech",
    kind: "Website",
    era: "Recent",
    caption: "A Web3 platform translating complex services into clear next steps.",
  },
  {
    src: "/reviews/recent/mahina-token.png",
    alt: "Mahina Token Web3 platform homepage",
    client: "Mahina Token",
    kind: "Web3",
    era: "Recent",
    caption: "A financial-services token story presented as a complete ecosystem.",
  },
  {
    src: "/reviews/video-swamp-rabbit.png",
    alt: "Swamp Rabbit Moving campaign video still",
    client: "Swamp Rabbit Moving",
    kind: "Video",
    caption: "A campaign story grounded in the people doing the work.",
  },
  {
    src: "/reviews/video-wiz-team.png",
    alt: "Wiz Team campaign video still",
    client: "Wiz Team",
    kind: "Video",
    caption: "Service expertise translated into visual proof.",
  },
  {
    src: "/reviews/video-mr-seafood.png",
    alt: "Mr. Seafood campaign video still",
    client: "Mr. Seafood",
    kind: "Video",
    caption: "A lively local story made for social discovery.",
  },
  {
    src: "/reviews/creative-ad-trial-masters.jpg",
    alt: "Trial Masters client advertising creative",
    client: "Trial Masters",
    kind: "Campaign",
    caption: "Campaign creative with a focused, memorable message.",
  },
  {
    src: "/reviews/case-modern-chiropractic.png",
    alt: "Modern Chiropractic website case study",
    client: "Modern Chiropractic",
    kind: "Website",
    caption: "Local positioning designed around patient confidence.",
  },
  {
    src: "/reviews/case-tesla-electric.png",
    alt: "Tesla Electric website case study",
    client: "Tesla Electric",
    kind: "Website",
    caption: "Service-area storytelling built to convert local demand.",
  },
  {
    src: "/reviews/case-stoney-craven.png",
    alt: "Stoney Craven website case study",
    client: "Stoney Craven",
    kind: "Website",
    caption: "A distinctive web presence with a sharper point of view.",
  },
  {
    src: "/reviews/case-disability-hc.png",
    alt: "Disability HC website case study",
    client: "Disability HC",
    kind: "Website",
    caption: "An accessible legal-services presence built for clarity.",
  },
  {
    src: "/reviews/case-masstar-signs.png",
    alt: "Masstar Signs website case study",
    client: "Masstar Signs",
    kind: "Website",
    caption: "A clearer digital storefront for a visual brand.",
  },
  {
    src: "/reviews/video-sofrito.png",
    alt: "Sofrito client campaign video still",
    client: "Sofrito",
    kind: "Video",
    caption: "Food, atmosphere, and personality captured for discovery.",
  },
  {
    src: "/reviews/video-andy-thomas.png",
    alt: "Andy Thomas client campaign video still",
    client: "Andy Thomas",
    kind: "Video",
    caption: "A people-first story shaped for a local audience.",
  },
  {
    src: "/reviews/video-local-fig.png",
    alt: "Local Fig client campaign video still",
    client: "Local Fig",
    kind: "Video",
    caption: "A distinctive hospitality story with a strong sense of place.",
  },
  {
    src: "/reviews/video-hair-studios.png",
    alt: "Hair Studios client campaign video still",
    client: "Hair Studios",
    kind: "Video",
    caption: "Service and personality presented through original video.",
  },
  {
    src: "/reviews/creative-stoney-social.png",
    alt: "Stoney Craven social campaign creative",
    client: "Stoney Craven",
    kind: "Social",
    caption: "A social system designed for recognizable repetition.",
  },
] as const;

export const HERITAGE_STRIP = [
  HERO_TEXTURE.primary,
  HERO_TEXTURE.secondary,
  HERO_TEXTURE.tertiary,
  HERO_TEXTURE.accent,
] as const;
