import type { LocationProfileSnapshot } from "@/lib/types/location-profile";

export function buildLlmsTxt(input: {
  profile: LocationProfileSnapshot;
  pageUrl: string;
  serviceNames: string[];
  categoryName?: string;
}): string {
  const { profile, pageUrl, serviceNames, categoryName } = input;
  const lines: string[] = [
    `# ${profile.name}`,
    "",
    "> AI-readable business facts generated by LocalMap / LocalSync.",
    "",
  ];

  if (profile.description) {
    lines.push("## About", profile.description, "");
  }

  lines.push("## Canonical facts");

  if (categoryName) {
    lines.push(`- Category: ${categoryName}`);
  }

  if (profile.phone) {
    lines.push(`- Phone: ${profile.phone}`);
  }

  if (profile.email) {
    lines.push(`- Email: ${profile.email}`);
  }

  if (profile.website) {
    lines.push(`- Website: ${profile.website}`);
  }

  const addressParts = [
    profile.addressLine1,
    profile.city,
    profile.state,
    profile.postalCode,
  ].filter(Boolean);

  if (addressParts.length > 0) {
    lines.push(`- Address: ${addressParts.join(", ")}`);
  }

  if (serviceNames.length > 0) {
    lines.push("", "## Services");
    for (const service of serviceNames) {
      lines.push(`- ${service}`);
    }
  }

  if (profile.sameAs.length > 0) {
    lines.push("", "## Profiles & listings");
    for (const url of profile.sameAs) {
      lines.push(`- ${url}`);
    }
  }

  if (profile.faqs && profile.faqs.length > 0) {
    lines.push("", "## FAQs");
    for (const faq of profile.faqs) {
      lines.push(`### ${faq.question}`, faq.answer, "");
    }
  }

  lines.push("", "## Structured page", `- ${pageUrl}`, "");

  return lines.join("\n");
}
